-- Autogenerated by Luapress v3.0
-- For available configuation options, see: fizzadar.com/luapress
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    url = '/Luapress/website/build',
    template = 'luapress',
    index_page = 'home'
}

return config
