-- Autogenerated by Luapress
local config = {
    -- Blog base url
    url = 'http://luapress.org',
    -- Blog title
    title = 'A Lone Ship',
    -- Template name
    template = 'luapress',
    -- Posts per page
    posts_per_page = 2,
    -- Link directories not files
    link_dirs = true,
    -- Control the output directories for posts & pages
    pages_dir = nil,
    posts_dir = nil,
    -- Separator to put inside <a id="more"></a> link
    more_separator = '',
    -- Select a page as the landing page (optional, no path or suffix)
    index = 'home',
}

return config
